### ISSUE TITLE
ENB isnt being mentioned in the readme.

### ISSUE THREAD

**Issue by Langmans** [cacophony-wj/LBS#1]
I think it's using Silent Horizons, but not sure. As the enb is the wabbajack file it might be nice to LonelyKitsune add a link to https://www.nexusmods.com/skyrimspecialedition/mods/21543

**Comment by cacophony-wj** [comment]
Thanks for the comment, I'll update the readme. But Wabbajack downloads the file directly from the Nexus and gives full download credit.
